import { Product } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    title: 'Fone Bluetooth Pro com Cancelamento de Ruído Integrado',
    category: 'Fone Bluetooth',
    store: 'Shopee',
    price: 89.90,
    oldPrice: 159.90,
    rating: 5.0,
    reviewsCount: 482,
    imageType: 'phone',
    tags: ['Destaque', '-44%'],
    clickCount: 15,
    affiliateLink: 'https://shopee.com.br/product-example-1',
    dateAdded: '2026-06-12'
  },
  {
    id: '2',
    title: 'Vestido Floral Verão Midi Fluido Alças Reguláveis',
    category: 'Moda Feminina',
    store: 'Shopee',
    price: 79.90,
    rating: 5.0,
    reviewsCount: 218,
    imageType: 'dress',
    tags: ['Novo'],
    clickCount: 8,
    affiliateLink: 'https://shopee.com.br/product-example-2',
    dateAdded: '2026-06-14'
  },
  {
    id: '3',
    title: 'Kit Organização Cozinha Prateleitas Multiúso Organizadoras',
    category: 'Acessórios Eletrônicos',
    store: 'Shopee',
    price: 64.90,
    oldPrice: 99.90,
    rating: 4.8,
    reviewsCount: 91,
    imageType: 'kitchen',
    tags: ['-35%'],
    clickCount: 23,
    affiliateLink: 'https://shopee.com.br/product-example-3',
    dateAdded: '2026-06-10'
  },
  {
    id: '4',
    title: 'Kit Skincare Completo Creme de Limpeza Toque Seco',
    category: 'Acessórios Eletrônicos',
    store: 'Shopee',
    price: 129.90,
    oldPrice: 189.90,
    rating: 4.9,
    reviewsCount: 347,
    imageType: 'lipstick',
    tags: ['-32%'],
    clickCount: 37,
    affiliateLink: 'https://shopee.com.br/product-example-4',
    dateAdded: '2026-06-11'
  },
  {
    id: '5',
    title: 'Caixa Bob Torre Som de Carro 12" E 10" Polegadas Rack móvel e Mesa de Som Modelo Bob Pintura Automotiva',
    category: 'Som Bluetooth',
    store: 'Shopee',
    price: 2989.45,
    rating: 4.9,
    reviewsCount: 12,
    imageType: 'sound',
    tags: ['Destaque'],
    clickCount: 42,
    affiliateLink: 'https://shopee.com.br/product-example-5',
    dateAdded: '2026-06-05'
  },
  {
    id: '6',
    title: 'Porta Chaves de Parede em Mdf Decorativo Preto Para Decoração Hall e Casa com Porta Cartas 5 Ganchos',
    category: 'Acessórios Eletrônicos',
    store: 'Shopee',
    price: 19.90,
    rating: 4.7,
    reviewsCount: 154,
    imageType: 'keys',
    tags: ['Campeão de Vendas'],
    clickCount: 55,
    affiliateLink: 'https://shopee.com.br/product-example-6',
    dateAdded: '2026-06-13'
  },
  {
    id: '7',
    title: 'Camiseta Masculina Blusa Brasil 3 Listras T-shirt Verão Manga Curta Camisa Algodão Premium',
    category: 'Celular', // Mapping to first app's categories if filtered, or custom
    store: 'Shopee',
    price: 39.90,
    rating: 4.9,
    reviewsCount: 812,
    imageType: 'shirt',
    tags: ['Shopee Oferta'],
    clickCount: 94,
    affiliateLink: 'https://shopee.com.br/product-example-7',
    dateAdded: '2026-06-13'
  },
  {
    id: '8',
    title: 'Quadro Placa Casal Namorix Filme e Foto Personalizado - Dia Dos Namorados Presente',
    category: 'Moda Feminina',
    store: 'Shopee',
    price: 19.99,
    oldPrice: 39.90,
    rating: 5.0,
    reviewsCount: 5154,
    imageType: 'netflix',
    tags: ['Mais Vendido'],
    clickCount: 120,
    affiliateLink: 'https://shopee.com.br/product-example-8',
    dateAdded: '2026-06-12'
  },
  {
    id: '9',
    title: 'Chaleira Elétrica 1,8L 1200W Unitermi Atacama Jarra Inox Alta Resistência',
    category: 'Acessórios Eletrônicos',
    store: 'Shopee',
    price: 40.99,
    rating: 4.8,
    reviewsCount: 129962,
    imageType: 'kettle',
    tags: ['Shopee Oferta'],
    clickCount: 88,
    affiliateLink: 'https://shopee.com.br/product-example-9',
    dateAdded: '2026-06-13'
  },
  {
    id: '10',
    title: '800mlgarrafa Térmica Água Squeeze Inox Academiaquente E Frio Garrafa Esportiva',
    category: 'Acessórios Eletrônicos',
    store: 'Shopee',
    price: 36.54,
    rating: 4.6,
    reviewsCount: 44632,
    imageType: 'bottle',
    tags: ['Desconto Relâmpago'],
    clickCount: 61,
    affiliateLink: 'https://shopee.com.br/product-example-10',
    dateAdded: '2026-06-14'
  },
  {
    id: '11',
    title: 'Barbeador E Cortador De Cabelo Em 1 Kemei Km-6558 Bivolt Sem Fio Recarregável',
    category: 'Acessórios Eletrônicos',
    store: 'Shopee',
    price: 48.89,
    rating: 4.7,
    reviewsCount: 12526,
    imageType: 'shaver',
    tags: ['Promoção'],
    clickCount: 44,
    affiliateLink: 'https://shopee.com.br/product-example-11',
    dateAdded: '2026-06-14'
  },
  {
    id: '12',
    title: 'Tênis Esportivo Confort Pro Corre',
    category: 'Moda Masculina',
    store: 'Shopee',
    price: 89.90,
    rating: 4.8,
    reviewsCount: 482,
    imageType: 'sneaker',
    tags: ['Destaque Semanal'],
    clickCount: 9,
    affiliateLink: 'https://shopee.com.br/product-example-12',
    dateAdded: '2026-06-12'
  },
  {
    id: '13',
    title: 'Vestido Midi Casual Clean',
    category: 'Moda Feminina',
    store: 'Shopee',
    price: 57.00,
    rating: 4.9,
    reviewsCount: 112,
    imageType: 'dress',
    tags: ['Destaque Semanal'],
    clickCount: 18,
    affiliateLink: 'https://shopee.com.br/product-example-13',
    dateAdded: '2026-06-10'
  }
];

export const INITIAL_CONFIG = {
  siteName: 'BASS Compre Mais',
  siteSubtitle: 'ACHADINHO',
  telegramLink: 'https://t.me/basscompremais',
  whatsappLink: 'https://chat.whatsapp.com/GgGv3HzJ',
  facebookLink: 'https://facebook.com/groups/basscompremais',
  freeShippingPromo: true,
  shopeeCashbackPromo: true
};
